### ISSUE TITLE
Youtube search breaks randomly

### ISSUE THREAD

**Issue by mattabullock** [wbliss/dj-yosof#14]
```Traceback (most recent call last):
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/discord/commands/core.py", line 124, in wrapped
    ret = await coro(arg)
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/discord/commands/core.py", line 976, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/nas/projects/dj-yosof/djyosof/cogs/youtube.py", line 57, in yt
    tracks = self.bot.players[AudioType.YOUTUBE].search(query)
  File "/home/nas/projects/dj-yosof/djyosof/players/youtube.py", line 78, in search
    return [
  File "/home/nas/projects/dj-yosof/djyosof/players/youtube.py", line 79, in <listcomp>
    YoutubeTrack.from_pytube(result) for result in Search(query).results[:5]
  File "/home/nas/projects/dj-yosof/djyosof/audio_types/youtube.py", line 24, in from_pytube
    yt.video_length = video.length
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/pytube/__main__.py", line 383, in length
    return int(self.vid_info.get('videoDetails', {}).get('lengthSeconds'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/nas/.local/share/virtualenvs/dj-yosof-nAsGa8Cr/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'```

**Comment by mattabullock** [comment]
Fixed by updating youtube lib
